/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_2800040823");

    // update field
    collection.fields.addAt(
      3,
      new Field({
        hidden: false,
        id: "select597064199",
        maxSelect: 2,
        name: "key_element",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: [
          "objectives - life cycle approach",
          "objectives - protection of health and environment",
          "objectives - plastic pollution",
          "objectives - marine environment",
          "principles - rio declaration",
          "principles - right to development and equity",
          "principles - common but differentiated responsibility",
          "principles - state sovereignty and international cooperation",
          "principles - right to development and equity",
          "principles - precautionary and polluter-pays principles",
          "principles - support for developing countries",
          "principles - use of best available science, indigenous and traditional knowledge",
          "party",
          "plastic",
          "plastic pollution",
          "plastic product",
          "plastic waste",
          "regional economic integration organization",
          "plastic products - national level",
          "Plastic products criteria",
          "products - measures",
          "products - monitoring",
          "products - global measures",
          "products - submission of proposal",
          "products - information need",
          "products - subsidiary body or review committee",
          "products - review committee",
          "products - guidance",
          "products - conference of the parties",
          "products - trade",
          "products - list of products",
          "chemicals - measures",
          "chemicals - traceability",
          "chemicals - list",
          "chemicals - criteria",
          "chemicals - risk management",
          "chemicals - plans",
          "chemicals - report",
          "chemicals - submissions",
          "chemicals - information may be as annex/criteria",
          "chemicals - process",
          "chemicals - technical and scientific committee",
          "chemicals - conference of the parties",
          "chemicals - dip con",
          "chemicals - annex list of chemicals",
          "chemicals - annex risk management",
          "registration and justification of exemptions",
          "phase-out dates",
          "statement of need",
          "public registry and transparency",
          "duration and expiry",
          "extension process and criteria",
          "availability of alternatives",
          "withdrawal and reapplication",
          "product design - design criteria",
          "product design - circular economy principles",
          "product design - sustainable alternatives and innovation",
          "sectoral guidance development",
          "non-discrimination clause trade",
          "alignment with international standards",
          "global production target",
          "lifecycle management measures",
          "data reporting obligations",
          "reporting format and guidance",
          "review mechanism for target adjustment",
          "prevent plastic releases and leakages",
          "prevent plastic pellets release and leakages",
          "manage fishing gear pollution",
          "research and monitoring \u2013 leakage pathways",
          "promote best available technologies and practices",
          "guidance by conference of parties (cop)",
          "consider national circumstances",
          "ensure environmentally sound management (esm)",
          "infrastructure development",
          "promote circular economy approaches",
          "prevent littering, open dumping/burning, ocean dumping",
          "fishing gear waste",
          "set national collection and recycling targets",
          "just transition - waste sector",
          "behavior change and awareness",
          "transboundary movement controls",
          "promote extended producer responsibility",
          "support implementation by conference of parties (cop)",
          "identify and monitor plastic pollution hotspots",
          "pollution removal and cleanup",
          "use of science and local knowledge",
          "stakeholder engagement and knowledge exchange",
          "guidance by conference of parties (cop)",
          "just transition - general principles and considering national context",
          "just transition - affected groups and workes",
          "just transition - monitoring and reporting of transition measures",
          "provision of financial support",
          "conditions for support - prioritization and needs",
          "structure and operation of the mechanism",
          "funding sources and replenishment",
          "funding uses - eligible activities",
          "capacity building and technical assistance",
          "technology transfer - terms and delivery",
          "international cooperation and coordination",
          "guidance by conference of parties (cop)",
          "establish compliance & implementation committee",
          "committee procedures and reporting",
          "national implementation plans",
          "stakeholder engagement in planning",
          "review and update of national plans",
          "national reporting obligations",
          "report format and timeline",
          "public access and transparency",
          "evaluation of convention effectiveness",
          "basis for evaluation",
          "modalities of evaluation process",
          "exchange of best practices and policy knowledge",
          "sharing scientific, traditional and indigenous knowledge",
          "information on risks and impacts of plastic pollution",
          "national focal points for information coordination",
          "online clearinghouse managed by the secretariat",
          "use of existing platforms and networks",
          "research, technologies and innovation exchange",
          "protection of confidential information",
          "public awareness and environmental education",
          "access to information and knowledge",
          "scientific research and data monitoring",
          "inclusion of traditional and local knowledge",
          "standardized monitoring methods and approaches",
          "capacity-building and multi-level training",
          "human health considerations",
          "conference of the parties \u2013 mandate and governance functions of the cop",
          "conference of the parties \u2013 rules of procedure and decision-making at cop meetings",
          "conference of the parties \u2013 frequency and modalities of cop sessions",
          "conference of the parties \u2013 authority to establish subsidiary bodies",
          "conference of the parties \u2013 engagement with international and non-state actors",
          "conference of the parties \u2013 observer participation and objection rules",
          "establishment of scientific and technical subsidiary bodies",
          "committees, panels, tors and working arrangements",
          "secretariat \u2013 functions and mandate",
          "support for conference of the parties meetings and parties",
          "reporting and documentation duties",
          "coordination with other international bodies",
          "hosting and institutional arrangements",
          "unep executive director as default secretariat",
          "cooperation and peaceful settlement of disputes",
          "declaration of compulsory arbitration and icj jurisdiction by parties",
          "declarations by regional economic integration organizations",
          "duration and revocation of declarations",
          "effect of expiry or revocation on ongoing proceedings",
          "conciliation procedures by conference of the parties",
          "procedure for amending the convention",
          "timeline and entry into force for amendments",
          "role of the depositary in amendment communication",
          "annexes as integral part of the convention",
          "scope of annexes limited to procedural and technical matters",
          "procedure for adoption and non-acceptance of new annexes",
          "amendment of annexes follows same procedure as adoption",
          "special provisions for parties with declarations (art. 27)",
          "voting rights of parties and organizations",
          "opening of the convention for signature",
          "locations and timeframe for signing the convention",
          "ratification, acceptance, approval, and accession",
          "obligations of regional economic integration organizations",
          "declaration of competence",
          "conditional entry into force of additional annexes and amendments",
          "conditions for entry into force of the convention",
          "entry into force for later ratifiers",
          "reservations - no reservations allowed",
          "withdrawal \u2013 possible after three years",
          "withdrawal \u2013 takes effect one year after notification",
          "depositary \u2013 un secretary-general",
          "authentic texts \u2013 equal authenticity of six official un languages",
        ],
      })
    );

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_2800040823");

    // update field
    collection.fields.addAt(
      3,
      new Field({
        hidden: false,
        id: "select597064199",
        maxSelect: 2,
        name: "key_element",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["plastic products - national level", "trade"],
      })
    );

    return app.save(collection);
  }
);
