/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./components/AppAlert.vue')['default']
    AppAuthorsAutoComplete: typeof import('./components/AppAuthorsAutoComplete.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppDeleteDialog: typeof import('./components/AppDeleteDialog.vue')['default']
    AppDocumentTypeAutoComplete: typeof import('./components/AppDocumentTypeAutoComplete.vue')['default']
    AppFilter: typeof import('./components/AppFilter.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavigationDrawer: typeof import('./components/AppNavigationDrawer.vue')['default']
    AppSessionAutoComplete: typeof import('./components/AppSessionAutoComplete.vue')['default']
    AppSnackbar: typeof import('./components/AppSnackbar.vue')['default']
    AppTopicsAutoComplete: typeof import('./components/AppTopicsAutoComplete.vue')['default']
    DocumentCreateDialog: typeof import('./components/DocumentCreateDialog.vue')['default']
    DocumentDialog: typeof import('./components/DocumentDialog.vue')['default']
    DocumentEditDialog: typeof import('./components/DocumentEditDialog.vue')['default']
    DocumentUploadDialog: typeof import('./components/DocumentUploadDialog.vue')['default']
    DraftTreatyEvolution: typeof import('./components/DraftTreatyEvolution.vue')['default']
    ExampleTree: typeof import('./components/ExampleTree.vue')['default']
    ListDocumentItem: typeof import('./components/ListDocumentItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopicsTaxonomyChart: typeof import('./components/TopicsTaxonomyChart.vue')['default']
    TopSessionSubmissionsChart: typeof import('./components/TopSessionSubmissionsChart.vue')['default']
    TopTopicsChart: typeof import('./components/TopTopicsChart.vue')['default']
    TopTopicsList: typeof import('./components/TopTopicsList.vue')['default']
    UserCreate: typeof import('./components/UserCreate.vue')['default']
    UserUpdate: typeof import('./components/UserUpdate.vue')['default']
  }
}
